# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# compile CXX with C:/msys64/mingw64/bin/c++.exe
CXX_DEFINES = -DGLM_FORCE_SWIZZLE -DNOMINMAX -DSPDLOG_COMPILED_LIB -DVK_NO_PROTOTYPES -D_USE_MATH_DEFINES -D__USE_MINGW_ANSI_STDIO=0 

CXX_INCLUDES = @CMakeFiles/Adypt.dir/includes_CXX.rsp

CXX_FLAGS = -DNDEBUG -std=gnu++17  -O3  -march=native -funroll-loops -mfpmath=sse -msse2 -msse3 -mssse3 -ffast-math -fpermissive  -Wno-format-y2k  -fno-strict-aliasing     -ffunction-sections  -fno-fat-lto-objects  -flto -fdata-sections

